# AWS Kinesis Stream
VALID_STREAM = 'ACTIVE'
SHARD_ID = 'shardId-000000000000'
ITERATOR_TYPE = 'TRIM_HORIZON'
ENHANCED_MONITORING = False
SHARD_LVL_METRICS = ['IteratorAgeMilliseconds']
PRODUCER_STREAM_FREQ = 5
CONSUMER_STREAM_FREQ = 30
CONSUMER_CATCHUP = 2