# AWS Kinesis Stream
STREAM_NAME = 'pxserve'
PARTITION_KEY = 'pxserve'
VALID_STREAM = 'ACTIVE'
SHARD_ID = 'shardId-000000000000'
ITERATOR_TYPE = 'TRIM_HORIZON'
ENHANCED_MONITORING = False
SHARD_LVL_METRICS = ['IteratorAgeMilliseconds']
PRODUCER_STREAM_FREQ = 0
CONSUMER_STREAM_FREQ = 10
CONSUMER_CATCHUP = 2

# Lightstream server
LIGHTSTREAMER_SUBSCRIPTION = 'MERGE'
DATA_TO_STREAM = ['UPDATE_TIME', 'BID', 'OFFER']